name: Daily Contribution

on:
  schedule:
    - cron: "30 5 * * *"   # 11 AM IST
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name:  Generate Engineering Log
        run: |
          DATE=$(date +'%Y-%m-%d')
          YEAR=$(date +'%Y')

          mkdir -p logs/$YEAR

          echo "# $DATE" >> logs/$YEAR/$DATE.md
          echo "## Work" >> logs/$YEAR/$DATE.md
          echo "- Worked on system design / Unity architecture" >> logs/$YEAR/$DATE.md
          echo "## Learning" >> logs/$YEAR/$DATE.md
          echo "- Improved problem solving" >> logs/$YEAR/$DATE.md

      - name: Commit & Push
        run: |
          git config --global user.name "Rithesh"
          git config --global user.email "[EMAIL_ADDRESS]"

          git add .
          git commit -m "Auto commit $(date)" || echo "No changes"

          git push